### ISSUE TITLE
-svc option in sample vpp?

### ISSUE THREAD

**Issue by gsilva2016** [Intel-Media-SDK/samples#15]
What was the -svc option for in the sample VPP project? This option does not appear to be implemented.

msdk_printf(MSDK_STRING("   [-svc id width height]- enable Scalable Video Processing mode\n"));

**Comment by fzhar** [comment]
Hello. This option has been deprecated in samples, and that message has been left by mistake. Thank you for pointing it out, we'll clean it up.

**Comment by onabiull** [comment]
Look this answered. Please feel free to file another issue at https://github.com/Intel-Media-SDK/MediaSDK if needed. This repo would be archived.
