### ISSUE TITLE
Coolness!

### ISSUE THREAD

**Issue by cameronelliott** [Intel-Media-SDK/samples#3]
It is incredibly cool to see this here on Github under BSD licensing.
A major Kudos to the people at Intel that made it happen.

So, if people want to do thing like submit pull requests for things like Visual Studio 2015 support, are you interested?
I am wondering if there is a live person behind the curtain, and also if you have issues like handling CLAs worked out yet.

Let me know if I might be able to answer questions on these topics.
Cameron

**Comment by amaslenn** [comment]
@cameron-elliott glad you are interested in MSDK samples!
Yes, we are interested in pulls. But depending on its size it can take some time to evaluate changes internally.

P.S. there are some folks behind the curtain, but shhh ;)
