### ISSUE TITLE
Unable to transcode an h264 video file to h265 file using sample_multi_transcode example

### ISSUE THREAD

**Issue by sivabudh** [Intel-Media-SDK/samples#7]
When I tried to run the sample application, I got this error.

```
$ ./sample_multi_transcode.exe -par transcoder.par
Multi Transcoding Sample Version 1.0.0.0

Par file is: transcoder.par


Return on error: error code -3, src\pipeline_transcode.cpp      2822


Return on error: error code -3, src\sample_multi_transcode.cpp  307

$ cat transcoder.par
-i::h264 data.mp4 -o::h265 datah265.mp4

```

My environment is Windows 10 running inside Parallels Desktop.
My IDE is Visual Studio 2015 Community Edition.
I built the project using Visual Studio and did not use the Perl script to build the projects.
The captured terminal above is from Windows Git Bash.

**Comment by fzhar** [comment]
Hello. You should not use .mp4 stream as input - samples work with plain non-muxed streams only (and .mp4 is container for several streams). Try to use test streams from samples package that can be downloaded from here: https://software.intel.com/en-us/intel-media-server-studio-support/code-samples
Also, make sure that you've installed Media SDK for Windows or Media Server Studio for Windows (https://software.intel.com/en-us/intel-media-server-studio) - these samples use library from those products.

**Comment by sivabudh** [comment]
Thanks,

I just downloaded test_stream.264 right now, and tried to convert it again, but still no dice. :(

```
$ cat transcoder.par
-i::h264 test_stream.264 -o::h265 datah265.265

$ ./sample_multi_transcode.exe -par transcoder.par
Multi Transcoding Sample Version 1.0.0.0

Par file is: transcoder.par


Return on error: error code -3, src\pipeline_transcode.cpp      2822


Return on error: error code -3, src\sample_multi_transcode.cpp  307
```

I have already installed Media SDK. Otherwise, I wouldn't have been able to build `sample_multi_transcode.exe` I think.

It's not because I'm running inside Parallels Desktop, is it? 

My processor is Intel Core i5 with Intel Iris 1536MB (Macbook Pro).

**Comment by fzhar** [comment]
That's quite strange. I suggest that there might be some DirectX compatibility issues because of Parallels Desktop (DirectX 9 or 11 is required for samples to work in HW-accelerated mode). You may try pure software mode first, by adding -sw to command line. Also, for first experiment I'd suggest to transcode to some format other that h265, because it requires additional plugin to be installed (as part of MSS) and configured. Try h264 to h264, just for test.

**Comment by sivabudh** [comment]
Finally! Thank you so much! I tested both combinations, and it turned out that I needed to use both the `-sw` command line flag *and* also not transcoding to h265!

I'm just playing around with the SDK right now. It actually took me a while to configure the project. I will hopefully be able to contribute some PR's of the changes I made to VC++ project to get it to build.

```
$ cat transcoder.par
-sw -i::h264 test_stream.264 -o::h264 output.264

$ ./sample_multi_transcode.exe -par transcoder.par
Multi Transcoding Sample Version 1.0.0.0

Par file is: transcoder.par

Pipeline surfaces number (DecPool): 19
MFX SOFTWARE Session 0 API ver 1.19 parameters:
Input  video: AVC
Output video: AVC
MFX dll: C:\Program Files (x86)\IntelSWTools\Intel(R)_Media_SDK_2016.0.2\bin\win32\libmfxsw32.dll

Session 0 was NOT joined with other sessions

Transcoding started
..
Transcoding finished

Common transcoding time is  1.30 sec
MFX session 0 transcoding PASSED:
Processing time: 1.19 sec
Number of processed frames: 101

The test PASSED
```

**Comment by sivabudh** [comment]
I will next follow the instructions on how to setup the additional plugin to get H265 transcoding to work.

https://software.intel.com/en-us/forums/intel-media-sdk/topic/603640
