### ISSUE TITLE
VPP doesn't support vertical mirror and rotation yet?

### ISSUE THREAD

**Issue by LoSealL** [Intel-Media-SDK/samples#8]
I'm exciting that MSDK samples have been put on the git and folks are maintaining this :)
I tried to complile sample_vpp and knocked into some problems:
 - First one is a complier error that MFX_PICSTRUCT_FIELD_SINGLE is not declared in headers (I have installed MSDK 2016.R2)
 - I ran some tests about sample_vpp (after remove MFX_PICSTRUCT_FIELD_SINGLE in the code), the _-mirror_ option works with horizontal mirror (-mirror 1), but failed with vertical mirror (-mirror 2) and the error code is mfx_err_unsuppoerted.
 - the _-rotate_ option has no effect with any arguments (90, 180, 270). It doesn't report any error, just does nothing to the image.

So, are there some features not ready for the VPP?
----------------------------
My test environment:
NUC i5-6260U (Iris 540)
Win 8.1 64bit
VS2015 Up3

**Comment by fzhar** [comment]
Hello. The latest samples source code on master branch is intended to be used with MSS 2017R2 (there's new API implemented). If you want to use samples for MSDK 2016R2 - please use source code with this tag: f7b203bc2e5d601079721aca3508522ce025e1c5
Another option - keep using latest samples, but install MSS 2017R2 for Windows. It includes latest library and API. All the samples will keep working with it except sample_camera - it requires additional header files and libraries from MSDK release.

**Comment by LoSealL** [comment]
Thanks for your reply!
I have installed MSS 2017R2, the MFX_PICSTRUCT_FIELD_SINGLE can be found now. However, the remaining two problems are not solved...

**Comment by fzhar** [comment]
I'll investigate it and come back with results.

**Comment by fzhar** [comment]
Hello.
We've investigated these issues - both of them are current library limitations:
- vertical mirroring is not supported yet
- rotation is implemented for D3D11 mode only - you have to provide -d3d11 option to sample_vpp to make it working

**Comment by LoSealL** [comment]
Thanks! Then I will use `rotate + horizontal mirroring` to act as a vertical mirror :)
